version: 2
updates:
    # Keep npm dependencies up to date
    - package-ecosystem: 'npm'
      directory: '/'
      target-branch: develop
      reviewers:
          - 'josh-fisher'
      schedule:
          interval: 'daily'
      labels:
          - 'npm dependencies'
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
