export const apiClientTemplate = `
/* tslint:disable */
/* eslint-disable */
/**
 * <%= apiClientClassName %>
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { <%= importApiModelClassName %> } from '../models/<%= dirname %>';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins, AdsConfiguration } from '../../helpers';

export class <%= apiClientClassName %> extends <%= apiModelClassName %> {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new AdsConfiguration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}

<%= extendable %>
`;
