
/* tslint:disable */
/* eslint-disable */
/**
 * SponsoredProductsClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { BidRecommendationsApi,SnapshotsApi,SuggestedKeywordsApi } from '../models/sponsored-products';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins, AdsConfiguration } from '../../helpers';

export class SponsoredProductsClient extends BidRecommendationsApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new AdsConfiguration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface SponsoredProductsClient extends BidRecommendationsApi,SnapshotsApi,SuggestedKeywordsApi {}
    applyMixins(SponsoredProductsClient, [BidRecommendationsApi,SnapshotsApi,SuggestedKeywordsApi])
    
