
/* tslint:disable */
/* eslint-disable */
/**
 * SponsoredBrandsExtraClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { BudgetRulesApi,BudgetRulesRecommendationApi,BudgetUsageApi,DefaultApi,KeywordRecommendationsApi,RecommendationsApi,SuggestionsApi } from '../models/sponsored-brands-extra';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins, AdsConfiguration } from '../../helpers';

export class SponsoredBrandsExtraClient extends BudgetRulesApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new AdsConfiguration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface SponsoredBrandsExtraClient extends BudgetRulesApi,BudgetRulesRecommendationApi,BudgetUsageApi,DefaultApi,KeywordRecommendationsApi,RecommendationsApi,SuggestionsApi {}
    applyMixins(SponsoredBrandsExtraClient, [BudgetRulesApi,BudgetRulesRecommendationApi,BudgetUsageApi,DefaultApi,KeywordRecommendationsApi,RecommendationsApi,SuggestionsApi])
    
