
/* tslint:disable */
/* eslint-disable */
/**
 * SponsoredProductsClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { AdGroupsApi,BidRecommendationsApi,CampaignNegativeKeywordsApi,CampaignsApi,KeywordsApi,NegativeKeywordsApi,NegativeProductTargetingApi,ProductAdsApi,ProductTargetingApi,ReportsApi,SnapshotsApi,SuggestedKeywordsApi } from '../models/sponsored-products';
import { Configuration } from '../models/configuration';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins } from '../../helpers';

export class SponsoredProductsClient extends AdGroupsApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new Configuration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface SponsoredProductsClient extends AdGroupsApi,BidRecommendationsApi,CampaignNegativeKeywordsApi,CampaignsApi,KeywordsApi,NegativeKeywordsApi,NegativeProductTargetingApi,ProductAdsApi,ProductTargetingApi,ReportsApi,SnapshotsApi,SuggestedKeywordsApi {}
    applyMixins(SponsoredProductsClient, [AdGroupsApi,BidRecommendationsApi,CampaignNegativeKeywordsApi,CampaignsApi,KeywordsApi,NegativeKeywordsApi,NegativeProductTargetingApi,ProductAdsApi,ProductTargetingApi,ReportsApi,SnapshotsApi,SuggestedKeywordsApi])
    
