
/* tslint:disable */
/* eslint-disable */
/**
 * SponsoredDisplayClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { AdGroupsApi,BidRecommendationsApi,BidRulesPreviewOnlyApi,BrandSafetyListOpenBetaApi,CampaignsApi,CreativesApi,NegativeTargetingApi,ProductAdsApi,ReportsApi,SnapshotsApi,TargetingApi,TargetingRecommendationsApi } from '../models/sponsored-display';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins, AdsConfiguration } from '../../helpers';

export class SponsoredDisplayClient extends AdGroupsApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new AdsConfiguration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface SponsoredDisplayClient extends AdGroupsApi,BidRecommendationsApi,BidRulesPreviewOnlyApi,BrandSafetyListOpenBetaApi,CampaignsApi,CreativesApi,NegativeTargetingApi,ProductAdsApi,ReportsApi,SnapshotsApi,TargetingApi,TargetingRecommendationsApi {}
    applyMixins(SponsoredDisplayClient, [AdGroupsApi,BidRecommendationsApi,BidRulesPreviewOnlyApi,BrandSafetyListOpenBetaApi,CampaignsApi,CreativesApi,NegativeTargetingApi,ProductAdsApi,ReportsApi,SnapshotsApi,TargetingApi,TargetingRecommendationsApi])
    
