
/* tslint:disable */
/* eslint-disable */
/**
 * SponsoredDisplayExtraClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { BrandSafetyDenyListDomainsApi,BrandSafetyRequestResultsApi,BrandSafetyRequestStatusApi,BudgetRulesApi,SnapshotAPIsApi,TargetingRecommendationsApi } from '../models/sponsored-display-extra';
import { Configuration } from '../models/configuration';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins } from '../../helpers';

export class SponsoredDisplayExtraClient extends BrandSafetyDenyListDomainsApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new Configuration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface SponsoredDisplayExtraClient extends BrandSafetyDenyListDomainsApi,BrandSafetyRequestResultsApi,BrandSafetyRequestStatusApi,BudgetRulesApi,SnapshotAPIsApi,TargetingRecommendationsApi {}
    applyMixins(SponsoredDisplayExtraClient, [BrandSafetyDenyListDomainsApi,BrandSafetyRequestResultsApi,BrandSafetyRequestStatusApi,BudgetRulesApi,SnapshotAPIsApi,TargetingRecommendationsApi])
    
